### ISSUE TITLE
The tupple ordering of traintuple and testtupple is different, is it a consision?

### ISSUE THREAD

**Issue by TheAlemazing** [SubstraFoundation/substra#158]
Just to be clear about this. 

Thank you

<img width="979" alt="image" src="https://user-images.githubusercontent.com/14184017/79077791-687ad900-7cf3-11ea-8f8c-e3e5a3d83a3e.png">

**Comment by jmorel** [comment]
Hello @TheAlemazing , do you mean that the testtuple section should be before the traintuple section alphabetically or do you mean that the relative order of items in the traintuple and testtuples tasks is not the same ?

If it's the former then this is because you need to understand what a traintuple is to be able to understand what a testtuple is.

If it's the latter then sure we could re-arrange the bullet points to have the same order, but the order doesn't make any difference when using the platform anyway since data is passed as a key-value dict and not as a tuple of values.

**Comment by TheAlemazing** [comment]
I mean the latter, it's good when re-arrange the bullet points for more consistency.
