### ISSUE TITLE
Generated docs: describe outputs returned by SDK methods

### ISSUE THREAD

**Issue by samlesu** [SubstraFoundation/substra#26]
We could use structure definition (dataclass, pydantic, marshmallow...) to parse the responses.
It would allow to have dynamic documentation.
~~It would allow also to return python object and to convert fields from camelCase to snake case.~~

EDIT: 
As pointed out by @jmorel, the SDK should not modify the field names returned by the backend. It will have to be done by the backend.

**Comment by jmorel** [comment]
While I'm all for parsing the responses and having dynamic documentation, I don't think we should convert from camelCase to snake_case in the SDK but rather have the backend return snake_case.

Otherwise we will have a discrepancy between the values users will receive and the one they have to provide when applying filters.

For example, when adding traintuples via a compute plan, users would see that each newly traintuple contains a `"compute_plan_id": "foo"` property. However to filter the list of traintuples to get those mathching this ID only, they would have to write `traintuple:computePlanID:foo`.  They'd have to know how to convert the snake_case value to the camelCase value.

Also, having the conversion in the SDK means that the frontend would have to either 1. implement its own conversion or 2. display the camelCase values. The first option strongly points in the direction of doing things in the backend (therefore doing things once and not twice) with the second one introduces discrepancies between our 2 only ways of interacting with the platform.

**Comment by samlesu** [comment]
Thanks @jmorel.

Good points! I fully agree with you, the camelCase to snake_case should be indeed done in the backend.

**Comment by samlesu** [comment]
This would be nice but could be done when we have a doc generated via sphinx and when the returned objects are formatted properly by the backend.
