### ISSUE TITLE
Create a common option for the output_format

### ISSUE THREAD

**Issue by maeldebon** [SubstraFoundation/substra#48]
It could be good to replace the `output_format` options (`--pretty`, `--json`, `--yaml`) by a common one (for example `--output` / `-o`) with the format as an argument.
The `--help` option could be easier to read like this 🙂 

Example:
For example, typing `substra list dataset --output pretty` instead of `substra list dataset --pretty`.

**Comment by jmorel** [comment]
While I agree that the help is not the easiest to read, I strongly disagree with having a global argument. It makes things just a bit harder to use. Maybe instead we should see if it's possible to specify how the yaml/json/pretty options are rendered in the help section?

**Comment by maeldebon** [comment]
> While I agree that the help is not the easiest to read, I strongly disagree with having a global argument. It makes things just a bit harder to use. Maybe instead we should see if it's possible to specify how the yaml/json/pretty options are rendered in the help section?

Ok, I'll have a look at this! 🙂

**Comment by Kelvin-M** [comment]
@jmorel Kubernetes use  `--output` / `-o`. I found it very nice because you can choose to output to stdout (with in this case `pretty`, `json`, `yaml`) but you can also chose to output it to a file without redirecting stdout to a file. Both solutions are good but having three options to output the result to stdout could be clustered into one with this  `--output` / `-o`.

**Comment by samlesu** [comment]
I would also be in favour of having a single option to define the output format `--output` rather than 3 different options.

**Comment by jmorel** [comment]
That's 3 against one, let's do it then ;)
